print("Starting to make a coffee")
print("Grinding coffee beans")
print("Boiling water")
print("Mixing boiled water with crushed coffee beans")
print("Pouring coffee into the cup")
print("Pouring some milk into the cup")
print("Coffee is ready!")
print("Write how many cups of coffee you will need:")
cups = int(input(">"))
print("For", cups,"cups of coffee you will need:")
print(cups * 200, "ml of water")
print(cups * 50, "ml of milk")
print(cups * 15, "ml of coffe beans")
